spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trayme
    driver-class-name:
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true