spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trayme
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
google:
  oauth:
    client-id:
    client-secret:
    redirect-uri:
