ALTER TABLE content
ADD COLUMN title VARCHAR(255), 
ADD COLUMN update_at DATETIME, 
ADD COLUMN content TEXT,
ADD COLUMN name VARCHAR(255),
ADD COLUMN who VARCHAR(255),
ADD COLUMN type VARCHAR(255);
ALTER TABLE content ADD COLUMN content_type VARCHAR(255);
